name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin ]
        runner: [ ubuntu-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        run: rustup target add ${{ matrix.target }}

      - name: Install cross (Linux/Windows only)
        if: matrix.target != 'x86_64-apple-darwin'
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: |
          if [ "${{ matrix.target }}" = "x86_64-apple-darwin" ]; then
            cargo build --release --target ${{ matrix.target }};
          else
            cross build --release --target ${{ matrix.target }};
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/affected